apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitwise-backend-deployment
  labels:
    app: splitwise-backend
  namespace: splitwise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: splitwise-backend
  template:
    metadata:
      labels:
        app: splitwise-backend

    spec:
      containers:
      - name: splitwise-backend
        image: 310997740486.dkr.ecr.ap-south-1.amazonaws.com/splitwise-backend:bb0409651d06431cd3585283d6f5e58d50bca157-3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # env:
        #   - name: VITE_BACKEND_URL
        #     value: "http://mern-backend-service.mern-app.svc.cluster.local:5000"
